spring.application.name=backend

# Default recipient email for safety ticket notifications
app.email.recipient=divyanshmishra55432@gmail.com

# Spring Mail Configuration (Uses environment variables or default settings)
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:divyanshmishra55432@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
